### ISSUE TITLE
Licence of the lexicon ?

### ISSUE THREAD

**Issue by Limezy** [gapmiss/berean-study-bible-with-strongs#2]
Hi ! I was wondering where your lexicons are coming from, and whether we could use them or not - if yes under which terms ?
Thanks !

**Comment by Limezy** [comment]
(Awesome Obsidian Bible project by the way)

**Comment by Limezy** [comment]
https://github.com/gapmiss/kingdom-study-tools-for-obsidian
OK I think the answer may be at the bottom of that README ?

**Comment by gapmiss** [comment]
Apologies for missing your issue. Yes, the license is the same as you found. Thank you for the kind words.
